import Link from 'next/link'
import Image from 'next/image'
import { 
  ArrowRight, 
  CheckCircle2, 
  XCircle,
  Users,
  PhoneCall,
  MessageSquare,
  Shield,
  AlertCircle,
  DollarSign,
  UserCheck,
  BookOpen,
  Route,
  Lock,
  TrendingDown
} from 'lucide-react'

export default function TreatmentLeadsPage() {
  return (
    <div className="overflow-hidden">
      {/* Hero Section */}
      <section className="relative bg-gradient-to-br from-slate-900 via-slate-800 to-brand-900 text-white overflow-hidden">
        {/* Background pattern */}
        <div className="absolute inset-0 opacity-10">
          <div className="absolute top-0 left-0 w-96 h-96 bg-brand-500 rounded-full blur-3xl -translate-x-1/2 -translate-y-1/2" />
          <div className="absolute bottom-0 right-0 w-96 h-96 bg-accent-500 rounded-full blur-3xl translate-x-1/2 translate-y-1/2" />
        </div>
        
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24 lg:py-32">
          <div className="max-w-4xl mx-auto text-center">
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold leading-tight mb-6">
              Own Your City's Bed Bug Jobs
            </h1>
            <p className="text-2xl sm:text-3xl text-slate-300 mb-8 font-semibold">
              Without the Google Ads Bidding War
            </p>
            
            <div className="bg-white/5 backdrop-blur-sm rounded-xl p-8 mb-8 max-w-3xl mx-auto border border-white/10">
              <p className="text-xl text-slate-200 mb-4">
                Get exclusive, high-intent bed bug treatment leads generated by our proprietary self-inspection app.
              </p>
              <div className="space-y-2 text-lg text-slate-300">
                <p className="flex items-center justify-center gap-2">
                  <CheckCircle2 className="w-5 h-5 text-emerald-400" />
                  One operator per territory
                </p>
                <p className="flex items-center justify-center gap-2">
                  <CheckCircle2 className="w-5 h-5 text-emerald-400" />
                  No shared leads
                </p>
                <p className="flex items-center justify-center gap-2">
                  <CheckCircle2 className="w-5 h-5 text-emerald-400" />
                  No bidding
                </p>
              </div>
              <p className="text-xl text-slate-200 mt-6 font-medium">
                Just treatment-ready homeowners sent directly to you.
              </p>
            </div>
            
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link 
                href="/territories" 
                className="inline-flex items-center justify-center gap-2 bg-accent-500 hover:bg-accent-600 text-white text-lg px-8 py-3 rounded-lg font-semibold transition-colors"
              >
                Check Territory Availability
                <ArrowRight className="w-5 h-5" />
              </Link>
              <a 
                href="tel:8169622111" 
                className="inline-flex items-center justify-center gap-2 text-white hover:bg-white/10 text-lg px-8 py-3 rounded-lg font-semibold transition-colors border border-white/20"
              >
                <PhoneCall className="w-5 h-5" />
                Call (816) 962-2111
              </a>
            </div>
          </div>
        </div>
        
        {/* Wave divider */}
        <div className="absolute bottom-0 left-0 right-0">
          <svg viewBox="0 0 1440 120" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0 120L60 110C120 100 240 80 360 70C480 60 600 60 720 65C840 70 960 80 1080 85C1200 90 1320 90 1380 90L1440 90V120H1380C1320 120 1200 120 1080 120C960 120 840 120 720 120C600 120 480 120 360 120C240 120 120 120 60 120H0Z" fill="#f8fafc"/>
          </svg>
        </div>
      </section>

      {/* The Problem With Google Ads */}
      <section className="py-24 bg-white">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl sm:text-4xl font-bold text-slate-900 mb-4">
              The Problem With Google Ads
            </h2>
            <p className="text-lg text-slate-600 italic">(You Already Know This)</p>
          </div>
          
          <div className="bg-red-50 rounded-2xl p-8 border-2 border-red-200 mb-8">
            <p className="text-2xl font-bold text-slate-900 mb-8 text-center">
              Google Ads for bed bugs are a money pit.
            </p>
            
            <div className="space-y-4">
              <div className="flex items-start gap-4">
                <DollarSign className="w-6 h-6 text-red-600 shrink-0 mt-1" />
                <div>
                  <p className="font-semibold text-slate-900">You pay $25–$60 per click</p>
                </div>
              </div>
              
              <div className="flex items-start gap-4">
                <Users className="w-6 h-6 text-red-600 shrink-0 mt-1" />
                <div>
                  <p className="font-semibold text-slate-900">You compete with 3–5 other operators on every job</p>
                </div>
              </div>
              
              <div className="flex items-start gap-4">
                <AlertCircle className="w-6 h-6 text-red-600 shrink-0 mt-1" />
                <div>
                  <p className="font-semibold text-slate-900">Half the calls are: "I'm not sure if it's bed bugs…"</p>
                </div>
              </div>
              
              <div className="flex items-start gap-4">
                <TrendingDown className="w-6 h-6 text-red-600 shrink-0 mt-1" />
                <div>
                  <p className="font-semibold text-slate-900">Price shoppers force you into a race to the bottom</p>
                </div>
              </div>
            </div>
            
            <div className="mt-8 pt-8 border-t border-red-300">
              <p className="text-lg text-slate-900 font-medium text-center">
                You're paying to educate homeowners and diagnose problems for free—before you even know if the job is real.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Here's Exactly What You're Buying */}
      <section className="py-24 bg-slate-50">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl sm:text-4xl font-bold text-slate-900 mb-4">
              Here's Exactly What You're Buying
            </h2>
          </div>
          
          <div className="bg-white rounded-2xl p-8 shadow-sm border border-slate-200 mb-8">
            <p className="text-xl text-slate-900 font-semibold mb-6">
              Inspection Pro Network gives you exclusive access to bed bug treatment demand in your territory.
            </p>
            
            <div className="space-y-3 mb-8">
              <div className="flex items-start gap-3">
                <XCircle className="w-5 h-5 text-red-500 shrink-0 mt-0.5" />
                <span className="text-slate-700">Not clicks.</span>
              </div>
              <div className="flex items-start gap-3">
                <XCircle className="w-5 h-5 text-red-500 shrink-0 mt-0.5" />
                <span className="text-slate-700">Not shared leads.</span>
              </div>
              <div className="flex items-start gap-3">
                <XCircle className="w-5 h-5 text-red-500 shrink-0 mt-0.5" />
                <span className="text-slate-700">Not people "just asking questions."</span>
              </div>
            </div>
            
            <p className="text-lg text-slate-700 mb-6">
              Homeowners are sent through our <strong className="text-slate-900">Bed Bug Self-Inspection App</strong>, where they can see what bed bugs look like, where they hide, and when professional treatment makes sense.
            </p>
            
            <p className="text-lg text-slate-700 mb-8">
              Many choose to use it. Some don't.
            </p>
            
            <div className="bg-brand-50 rounded-xl p-6 border border-brand-200 mb-8">
              <p className="text-lg font-semibold text-slate-900 mb-4">
                Either way, by the time they request help, they already believe treatment is needed.
              </p>
              
              <p className="text-slate-900 font-medium mb-3">When that request comes in:</p>
              <ul className="space-y-2 text-slate-700">
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0 mt-0.5" />
                  <span>It goes to one operator only</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0 mt-0.5" />
                  <span>There is no bidding and no sharing</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0 mt-0.5" />
                  <span>You're the only professional they see</span>
                </li>
              </ul>
              
              <p className="text-lg font-semibold text-slate-900 mt-6">
                These are treatment-intent homeowners, not "maybe" calls.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Why This Beats Traditional Lead Gen */}
      <section className="py-24 bg-white">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl sm:text-4xl font-bold text-slate-900 mb-4">
              Why This Beats Traditional Lead Gen
            </h2>
          </div>
          
          <div className="bg-white rounded-2xl p-8 shadow-sm border-2 border-slate-200">
            <p className="text-xl text-slate-900 font-semibold mb-6">
              Most lead companies sell access to confusion.
            </p>
            
            <p className="text-lg text-slate-700 mb-6 font-medium">
              You pay to answer:
            </p>
            
            <div className="bg-red-50 rounded-xl p-6 border border-red-200 mb-8">
              <ul className="space-y-3 text-slate-700">
                <li className="flex items-start gap-3">
                  <AlertCircle className="w-5 h-5 text-red-600 shrink-0 mt-0.5" />
                  <span>"I think I saw something…"</span>
                </li>
                <li className="flex items-start gap-3">
                  <AlertCircle className="w-5 h-5 text-red-600 shrink-0 mt-0.5" />
                  <span>"Can you come look for free?"</span>
                </li>
                <li className="flex items-start gap-3">
                  <AlertCircle className="w-5 h-5 text-red-600 shrink-0 mt-0.5" />
                  <span>"I'm calling three other companies too."</span>
                </li>
              </ul>
            </div>
            
            <div className="bg-emerald-50 rounded-xl p-6 border-2 border-emerald-200 mb-8">
              <p className="text-lg font-semibold text-slate-900 mb-4">
                We remove that layer.
              </p>
              
              <p className="text-lg text-slate-700 mb-4">
                The app educates homeowners before they reach you, so your conversations start at treatment, not diagnosis.
              </p>
              
              <div className="space-y-2 text-slate-700">
                <p className="flex items-start gap-2">
                  <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0 mt-0.5" />
                  <span>You don't waste time qualifying.</span>
                </p>
                <p className="flex items-start gap-2">
                  <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0 mt-0.5" />
                  <span>You don't compete on price.</span>
                </p>
                <p className="flex items-start gap-2">
                  <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0 mt-0.5" />
                  <span>You just handle the job.</span>
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* The Bottom Line */}
      <section className="py-24 bg-slate-50">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl sm:text-4xl font-bold text-slate-900 mb-4">
              The Bottom Line
            </h2>
          </div>
          
          <div className="bg-white rounded-2xl p-8 shadow-sm border-2 border-brand-200">
            <div className="space-y-4 mb-8">
              <p className="text-lg text-slate-700">
                You're not paying for traffic.
              </p>
              <p className="text-lg text-slate-700">
                You're not buying leads by the pound.
              </p>
            </div>
            
            <div className="bg-brand-50 rounded-xl p-6 border-2 border-brand-300">
              <p className="text-xl font-bold text-slate-900 mb-4 text-center">
                You're securing exclusive access to bed bug treatment requests in your territory.
              </p>
              <p className="text-xl font-semibold text-slate-900 text-center">
                That's the offer.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* The 3-Step Qualification Process */}
      <section className="py-24 bg-white">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl sm:text-4xl font-bold text-slate-900 mb-4">
              The 3-Step Qualification Process
            </h2>
          </div>
          
          <div className="grid md:grid-cols-3 gap-8">
            {/* Step 1 */}
            <div className="bg-slate-50 rounded-2xl p-8 border border-slate-200">
              <div className="w-12 h-12 rounded-full bg-brand-500 text-white flex items-center justify-center text-xl font-bold mb-6">
                1
              </div>
              <h3 className="text-xl font-bold text-slate-900 mb-4 flex items-center gap-2">
                <UserCheck className="w-6 h-6 text-brand-600" />
                The App Qualifies the Homeowner
              </h3>
              <p className="text-slate-700 mb-4">
                Homeowners are guided through a structured self-inspection:
              </p>
              <ul className="space-y-2 text-slate-700">
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0 mt-1" />
                  <span>What bed bugs actually look like</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0 mt-1" />
                  <span>Where to check</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0 mt-1" />
                  <span>Which signs matter</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0 mt-1" />
                  <span>When professional treatment is necessary</span>
                </li>
              </ul>
              <p className="text-sm text-slate-600 mt-4 italic">
                This replaces the "free inspection" call entirely.
              </p>
            </div>
            
            {/* Step 2 */}
            <div className="bg-slate-50 rounded-2xl p-8 border border-slate-200">
              <div className="w-12 h-12 rounded-full bg-brand-500 text-white flex items-center justify-center text-xl font-bold mb-6">
                2
              </div>
              <h3 className="text-xl font-bold text-slate-900 mb-4 flex items-center gap-2">
                <BookOpen className="w-6 h-6 text-brand-600" />
                Education & Confirmation
              </h3>
              <p className="text-slate-700 mb-4">
                The app educates homeowners on:
              </p>
              <ul className="space-y-2 text-slate-700">
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0 mt-1" />
                  <span>Why DIY and sprays fail</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0 mt-1" />
                  <span>When heat or professional treatment is required</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0 mt-1" />
                  <span>What to expect from a real bed bug expert</span>
                </li>
              </ul>
              <p className="text-sm text-slate-600 mt-4 italic">
                By the time they reach out, they already understand the problem.
              </p>
            </div>
            
            {/* Step 3 */}
            <div className="bg-slate-50 rounded-2xl p-8 border border-slate-200">
              <div className="w-12 h-12 rounded-full bg-brand-500 text-white flex items-center justify-center text-xl font-bold mb-6">
                3
              </div>
              <h3 className="text-xl font-bold text-slate-900 mb-4 flex items-center gap-2">
                <Route className="w-6 h-6 text-brand-600" />
                Exclusive Lead Routing
              </h3>
              <p className="text-slate-700 mb-4">
                When treatment is needed:
              </p>
              <ul className="space-y-2 text-slate-700">
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0 mt-1" />
                  <span>The request is routed to one operator only</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0 mt-1" />
                  <span>No shared data</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0 mt-1" />
                  <span>No auctions</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0 mt-1" />
                  <span>No competitors seeing the same homeowner</span>
                </li>
              </ul>
              <p className="text-sm font-semibold text-emerald-700 mt-4">
                If you own the territory, you get every qualified lead.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Comparison Table */}
      <section className="py-24 bg-slate-50">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl sm:text-4xl font-bold text-slate-900 mb-4">
              How This Compares at a Glance
            </h2>
          </div>
          
          <div className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="bg-slate-100 border-b border-slate-200">
                    <th className="px-6 py-4 text-left text-sm font-semibold text-slate-900">Feature</th>
                    <th className="px-6 py-4 text-left text-sm font-semibold text-red-600">Google Ads / Lead Marketplaces</th>
                    <th className="px-6 py-4 text-left text-sm font-semibold text-emerald-600">Inspection Pro Network</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-200">
                  <tr>
                    <td className="px-6 py-4 text-sm font-medium text-slate-900">Exclusivity</td>
                    <td className="px-6 py-4 text-sm text-slate-700">Shared with 3–5 competitors</td>
                    <td className="px-6 py-4 text-sm text-slate-700 font-semibold text-emerald-700">100% exclusive</td>
                  </tr>
                  <tr className="bg-slate-50">
                    <td className="px-6 py-4 text-sm font-medium text-slate-900">Cost</td>
                    <td className="px-6 py-4 text-sm text-slate-700">Pay-per-click (even bad leads)</td>
                    <td className="px-6 py-4 text-sm text-slate-700 font-semibold text-emerald-700">Fixed monthly cost</td>
                  </tr>
                  <tr>
                    <td className="px-6 py-4 text-sm font-medium text-slate-900">Lead Quality</td>
                    <td className="px-6 py-4 text-sm text-slate-700">"I think I saw a bug…"</td>
                    <td className="px-6 py-4 text-sm text-slate-700 font-semibold text-emerald-700">Pre-qualified via app</td>
                  </tr>
                  <tr className="bg-slate-50">
                    <td className="px-6 py-4 text-sm font-medium text-slate-900">Competition</td>
                    <td className="px-6 py-4 text-sm text-slate-700">Price wars</td>
                    <td className="px-6 py-4 text-sm text-slate-700 font-semibold text-emerald-700">You're the only option</td>
                  </tr>
                  <tr>
                    <td className="px-6 py-4 text-sm font-medium text-slate-900">Control</td>
                    <td className="px-6 py-4 text-sm text-slate-700">Platform-dependent</td>
                    <td className="px-6 py-4 text-sm text-slate-700 font-semibold text-emerald-700">Territory ownership</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </section>

      {/* Visual Overview of the System */}
      <section className="py-24 bg-white">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl sm:text-4xl font-bold text-slate-900 mb-4">
              Visual Overview of the System
            </h2>
          </div>
          
          <div className="bg-slate-50 rounded-2xl p-8 border border-slate-200">
            <div className="relative w-full aspect-[16/10] rounded-lg overflow-hidden mb-6">
              <Image
                src="/lead-generation-infographic.png"
                alt="How Inspection Pro Network Generates High-Intent Leads - Homeowners self-inspect through the app, get educated on bed bug treatment, and treatment-ready leads are routed to one operator per territory"
                fill
                className="object-contain"
                priority
              />
            </div>
            <p className="text-center text-slate-600 italic">
              Homeowners self-inspect → get educated → treatment-ready leads go to one operator per territory.
            </p>
          </div>
        </div>
      </section>

      {/* The One-Operator Rule */}
      <section className="py-24 bg-slate-50">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl sm:text-4xl font-bold text-slate-900 mb-4">
              The One-Operator Rule
            </h2>
            <p className="text-lg text-slate-600 italic">(This Is Non-Negotiable)</p>
          </div>
          
          <div className="bg-emerald-50 rounded-2xl p-8 border-2 border-emerald-200 mb-8">
            <div className="flex items-center justify-center gap-3 mb-6">
              <Lock className="w-8 h-8 text-emerald-600" />
              <p className="text-2xl font-bold text-slate-900">
                We do not sell shared leads.
              </p>
            </div>
            <p className="text-xl text-slate-900 font-semibold text-center mb-6">
              We do not open the same territory to multiple companies.
            </p>
            
            <div className="bg-white rounded-xl p-6 border border-emerald-300">
              <p className="text-lg text-slate-900 font-medium mb-4">Once a territory is assigned:</p>
              <ul className="space-y-3">
                <li className="flex items-center gap-3">
                  <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0" />
                  <span className="text-slate-900 font-semibold">It is locked</span>
                </li>
                <li className="flex items-center gap-3">
                  <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0" />
                  <span className="text-slate-900 font-semibold">No overlap</span>
                </li>
                <li className="flex items-center gap-3">
                  <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0" />
                  <span className="text-slate-900 font-semibold">No internal competition</span>
                </li>
              </ul>
              <p className="text-lg text-slate-900 font-semibold mt-6 text-center">
                This is how you escape the bidding war entirely.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Territory Availability */}
      <section className="py-24 bg-white">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl sm:text-4xl font-bold text-slate-900 mb-4">
              Territory Availability
            </h2>
            <p className="text-lg text-slate-600 italic">(Scarcity Matters)</p>
          </div>
          
          <div className="bg-white rounded-2xl p-8 shadow-sm border border-slate-200">
            <p className="text-xl text-slate-900 font-semibold mb-6 text-center">
              We are currently opening territories for one operator only.
            </p>
            
            <div className="space-y-4 mb-8">
              <div className="flex items-start gap-3">
                <Lock className="w-6 h-6 text-brand-600 shrink-0 mt-1" />
                <div>
                  <p className="font-semibold text-slate-900 mb-1">Once the agreement is signed:</p>
                  <ul className="space-y-2 text-slate-700">
                    <li className="flex items-start gap-2">
                      <span className="text-brand-600">•</span>
                      <span>The territory is closed</span>
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-brand-600">•</span>
                      <span>It remains exclusive for the term</span>
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="text-brand-600">•</span>
                      <span>No additional operators are added</span>
                    </li>
                  </ul>
                </div>
              </div>
              
              <div className="bg-amber-50 rounded-xl p-6 border border-amber-200 mt-6">
                <p className="text-lg font-semibold text-slate-900 text-center">
                  Availability is limited by design.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Pricing Philosophy */}
      <section className="py-24 bg-slate-50">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl sm:text-4xl font-bold text-slate-900 mb-4">
              Pricing Philosophy
            </h2>
          </div>
          
          <div className="bg-white rounded-2xl p-8 shadow-sm border-2 border-slate-200">
            <div className="space-y-4 mb-8">
              <div className="flex items-start gap-3">
                <CheckCircle2 className="w-6 h-6 text-emerald-600 shrink-0 mt-1" />
                <div>
                  <p className="text-lg text-slate-900 font-semibold">Monthly pricing</p>
                  <p className="text-slate-700">Predictable</p>
                </div>
              </div>
              
              <div className="flex items-start gap-3">
                <CheckCircle2 className="w-6 h-6 text-emerald-600 shrink-0 mt-1" />
                <div>
                  <p className="text-lg text-slate-900 font-semibold">Typically less than the cost of two Google Ads leads</p>
                </div>
              </div>
              
              <div className="flex items-start gap-3">
                <CheckCircle2 className="w-6 h-6 text-emerald-600 shrink-0 mt-1" />
                <div>
                  <p className="text-lg text-slate-900 font-semibold">No contracts designed to trap you</p>
                  <p className="text-slate-700 italic">You either see the value—or you don't</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-24 bg-gradient-to-br from-brand-600 to-brand-700 text-white">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <Shield className="w-12 h-12 mx-auto mb-6 opacity-90" />
          <h2 className="text-3xl sm:text-4xl font-bold mb-6">
            Check Territory Availability Now
          </h2>
          <p className="text-xl text-brand-100 mb-8 max-w-2xl mx-auto">
            The next step is simple.
          </p>
          
          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center mb-6">
            <Link 
              href="/territories"
              className="inline-flex items-center justify-center gap-2 bg-white text-brand-600 hover:bg-brand-50 text-lg px-8 py-3 rounded-lg font-semibold transition-colors"
            >
              View Available Territories
              <ArrowRight className="w-5 h-5" />
            </Link>
            <a 
              href="tel:8169622111" 
              className="inline-flex items-center justify-center gap-2 bg-brand-500 hover:bg-brand-400 text-white text-lg px-8 py-3 rounded-lg font-semibold transition-colors border border-white/20"
            >
              <PhoneCall className="w-5 h-5" />
              Call (816) 962-2111
            </a>
            <a 
              href="sms:8169622111" 
              className="inline-flex items-center justify-center gap-2 bg-brand-500 hover:bg-brand-400 text-white text-lg px-8 py-3 rounded-lg font-semibold transition-colors border border-white/20"
            >
              <MessageSquare className="w-5 h-5" />
              Text
            </a>
          </div>
        </div>
      </section>
    </div>
  )
}
